### ISSUE TITLE
Backround Plug In aus, Theme bleibt an

### ISSUE THREAD

**Issue by KainEhrenmann** [YukiGasai/BetterDiscord#13]
# **Backround Plug In**

Lieber ***Richard***, wenn mann das Plug In ausmacht bleibt das Theme geladen. 
[**Bitte beheben.**](https://github.com/YukiGasai/BetterDiscord/blob/master/plugins/Background.plugin.js)

Wie ich immer zu pflegen vermag:
>Ohne Fleiß,
>kein Preis!

Mit freundlichen Grüßen
***Patrice Le Wieczorek***

**Comment by YukiGasai** [comment]
Ist behoben
