### ISSUE TITLE
Set Avatar Ordner Pfad funktioniert nicht

### ISSUE THREAD

**Issue by KainEhrenmann** [YukiGasai/BetterDiscord#3]
![image](https://user-images.githubusercontent.com/70284479/91336600-6e6ce480-e7d2-11ea-87b7-88cff0af440a.png)
Ich habe einen Ordner erstellt, dann bilder eingefügt dann diesen Ordner Pfad eingefügt und es hat nichts funktioniert nachdem ich speichern gedrückt habe, Fehler kam als ich auf Open geklickt habe. 

[Link](https://github.com/YukiGasai/BetterDiscord/blob/master/plugins/AvatarChanger.plugin.js)

MfG Patrik Wieczorek
Betriebsleitung

**Comment by YukiGasai** [comment]
Pfad wurde mit Leerzeichen eingegeben
Kein Fehler
