### ISSUE TITLE
Set Avatar ,es wird kein Avatar geändert 

### ISSUE THREAD

**Issue by KainEhrenmann** [YukiGasai/BetterDiscord#4]
![image](https://user-images.githubusercontent.com/70284479/91338036-978e7480-e7d4-11ea-831e-d20f6d543f68.png)

Lieber Richard, ich habe alles verlinkt wie es mir der Meister gezeigt hat, nun aber wo das Plugin nach wiederholten male nicht mein PB ändert und ich diese Fehlermeldung bekomme(siehe oben). Die Fehlermeldung erscheint wenn ich das Plug in starte.

[Link](https://github.com/YukiGasai/BetterDiscord/blob/master/plugins/AvatarChanger.plugin.js)

MfG Patrik Emanuel Wieczorek
Chefkoch

**Comment by KainEhrenmann** [comment]
![image](https://user-images.githubusercontent.com/70284479/91340274-07522e80-e7d8-11ea-96cd-0797d1803403.png)
neurdings habe ich diese Fehlermeldung , nachdem ich den Pfad ohne onedrive gemacht habe. Der Fehler kommt wenn ich das Plug In starte

**Comment by YukiGasai** [comment]
Nicht reproduzierbar.
Habe alle Pfade im OneDrive mit Leerzeichen und es funktioniert.

**Comment by KainEhrenmann** [comment]
Verschoben

**Comment by KainEhrenmann** [comment]
Du sollst arbeiten


YukiGasai <notifications@github.com> schrieb am Mi., 23. Sep. 2020, 11:18:
