### ISSUE TITLE
Image Downloader Standart Pfade funken nicht

### ISSUE THREAD

**Issue by KainEhrenmann** [YukiGasai/BetterDiscord#5]
Lieber Richard, hiermit melde ich einen Bug bei dem Image Downloader kann es passieren das die Standart Pfade nicht richtig funktionieren durch meine Kompetenz hab ich es allein hinbekommen. Das Problem ich weiß nicht wie. Wäre gut wenn du dich darum kümmerst, weil du weißt es kommen nach mir nur (Idioten).

[Link](https://github.com/YukiGasai/BetterDiscord/blob/master/plugins/ImageDownloader.plugin.js)

MfG Patrice Wieczorek
Spargelstecher

**Comment by YukiGasai** [comment]
Konnte Bug reproduzieren arbeite an fix.

**Comment by YukiGasai** [comment]
Bug behoben fehlende / am Standardpfad 
Bitte testen und Bug schließen, wenn es bei dir funktioniert.

**Comment by KainEhrenmann** [comment]
Funkt, Meister
